[database]
cache_store = "sqlite:///app/data/gorse_cache.db"
data_store = "sqlite:///app/data/gorse_data.db"

[server]
default_n = 100

[recommend]
fallback_recommend = ["item_to_item", "popular", "latest"]

[recommend.data_source]
positive_feedback_types = ["like", "repost", "comment"]
read_feedback_types = ["read"]
negative_feedback_types = ["dislike"]

[recommend.collaborative]
enable_index = true

[recommend.item_to_item]
enable_index = true

[recommend.offline]
check_recommend_period = 1
explore_recommend = { popular = 0.3, latest = 0.2, collaborative = 0.5 }

[recommend.popular]
popular_window = "720h"
